#include "luca/pbmp.h"
#include <stdio.h>
#include <string.h>
#include <unistd.h>
#include <sys/socket.h>
#include <sys/un.h>
#include <sys/stat.h>
static int field(const char*s,const char*k,char*out,size_t n){char q[80];snprintf(q,sizeof q,"\"%s\"",k);const char*p=strstr(s,q);if(!p)return-1;p=strchr(p+strlen(q),':');if(!p)return-1;while(*++p==' ');if(*p!='\"')return-1;p++;const char*e=strchr(p,'\"');if(!e)return-1;size_t z=(size_t)(e-p);if(z>=n)return-1;memcpy(out,p,z);out[z]=0;return 0;}
int luca_pbmp_response(const char*req,const struct luca_pbmp_state*s,char*out,size_t n){char id[128],m[128];if(field(req,"id",id,sizeof id)||field(req,"method",m,sizeof m))return-1;const char*r=NULL;char dyn[768];if(!strcmp(m,"pbmp.info"))r="{\"protocol\":\"PBMP/1\",\"implementation\":\"luca\",\"version\":\"0.1.2\"}";else if(!strcmp(m,"capabilities.list"))r="{\"capabilities\":[\"pbmp.info\",\"capabilities.list\",\"bot.info\",\"networks.list\"]}";else if(!strcmp(m,"bot.info")){snprintf(dyn,sizeof dyn,"{\"implementation\":\"luca\",\"version\":\"0.1.2\",\"nick\":\"%s\",\"state\":\"%s\"}",s->nick,s->connected?"online":"offline");r=dyn;}else if(!strcmp(m,"networks.list")){snprintf(dyn,sizeof dyn,"{\"networks\":[{\"name\":\"%s\",\"state\":\"%s\"}]}",s->network,s->connected?"connected":"disconnected");r=dyn;}else if(!strcmp(m,"channels.list")){if(s->channel&&s->channel[0])snprintf(dyn,sizeof dyn,"{\"channels\":[{\"network\":\"%s\",\"name\":\"%s\",\"state\":\"%s\"}]}",s->network,s->channel,s->connected?"configured":"disconnected");else snprintf(dyn,sizeof dyn,"{\"channels\":[]}");r=dyn;}if(r)return snprintf(out,n,"{\"pbmp\":1,\"type\":\"response\",\"id\":\"%s\",\"ok\":true,\"result\":%s}\n",id,r)>=(int)n?-1:0;return snprintf(out,n,"{\"pbmp\":1,\"type\":\"response\",\"id\":\"%s\",\"ok\":false,\"error\":{\"code\":\"not_supported\",\"message\":\"method not supported\"}}\n",id)>=(int)n?-1:0;}
int luca_pbmp_serve(const char*path,const struct luca_pbmp_state*s){int fd=socket(AF_UNIX,SOCK_STREAM,0);if(fd<0)return-1;struct sockaddr_un a={0};a.sun_family=AF_UNIX;if(strlen(path)>=sizeof a.sun_path){close(fd);return-1;}snprintf(a.sun_path,sizeof a.sun_path,"%s",path);unlink(path);if(bind(fd,(struct sockaddr*)&a,sizeof a)||chmod(path,0600)||listen(fd,4)){close(fd);unlink(path);return-1;}for(;;){int c=accept(fd,NULL,NULL);if(c<0)continue;char in[2048],out[4096];ssize_t z=read(c,in,sizeof in-1);if(z>0){in[z]=0;if(!luca_pbmp_response(in,s,out,sizeof out))write(c,out,strlen(out));}close(c);}return 0;}
